import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { buildSeoRoutes } from '../src/seo/routes.ts'
import { toHeadMeta } from '../src/seo/metaCopy.ts'

const root = resolve(import.meta.dirname, '..')
const routes = buildSeoRoutes()

const map: Record<string, ReturnType<typeof toHeadMeta>> = {}
for (const entry of routes) {
  map[entry.path] = toHeadMeta(entry)
}

const ts = `/* Auto-generated by scripts/generate-seo-head.ts — do not edit. */
export type GeneratedHeadMeta = {
  title: string
  description: string
  canonical: string
  ogImage: string
  index: boolean
}

export const SEO_HEAD_META: Record<string, GeneratedHeadMeta> = ${JSON.stringify(map, null, 2)} as const
`

writeFileSync(resolve(root, 'src/seo/headMeta.generated.ts'), ts, 'utf8')
writeFileSync(resolve(root, 'public/seo-head.json'), JSON.stringify(map, null, 2), 'utf8')

console.log(`SEO head meta: ${Object.keys(map).length} paths written`)
