import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { getIndexableSeoRoutes, getSeoAllowlistPaths } from '../src/seo/routes.ts'
import { SITE_URL } from '../src/seo/siteConfig.ts'

const root = resolve(import.meta.dirname, '..')
const lastmod = new Date().toISOString().slice(0, 10)

const indexableRoutes = getIndexableSeoRoutes()
const allowlistPaths = getSeoAllowlistPaths()

const sitemapEntries = indexableRoutes
  .map((entry) => {
    const priority = entry.priority ?? 0.6
    const changefreq = entry.changefreq ?? 'monthly'
    return `  <url>
    <loc>${SITE_URL}${entry.path === '/' ? '' : entry.path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>
  </url>`
  })
  .join('\n')

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries}
</urlset>
`

writeFileSync(resolve(root, 'public/sitemap.xml'), sitemap, 'utf8')
writeFileSync(
  resolve(root, 'public/seo-allowlist.json'),
  JSON.stringify(allowlistPaths, null, 2),
  'utf8',
)
writeFileSync(
  resolve(root, 'src/seo/allowlist.generated.ts'),
  `/** Generated by scripts/generate-sitemap.ts — do not edit manually */\nexport const SEO_ALLOWLIST = new Set<string>(${JSON.stringify(allowlistPaths, null, 2)})\n`,
  'utf8',
)

console.log(`Generated sitemap with ${indexableRoutes.length} URLs and allowlist with ${allowlistPaths.length} paths.`)
